# filter alarms contain label
filter:
  label:
    key: [ demo,^demo*$,^test$ ]
    value: [ demo,^demo$, ^test$ ]
    combination:
      - demo: demo
      - ^(demo)$: ^demo$
      - demo: ^demo$

# replace alarms label key value
replace:


# match label choose receiver
dispatch:
  labelExtractSender:
    - job: ^who-(.*)$  # exp. who-slack  extract: [slack] match [receivers.name]
  labelMatch:
    - key: [ demo,^demo*$ ]
      value: [ demo,^demo$ ]
      combination:
        - demo: demo
        - ^(demo)$: ^demo$
        - demo: ^demo$
      receiver: [ slack,tg ]

# receiver name need uniq
receivers:
  - name: "slack"
    type: "slack"
    webhook: https://hooks.slack.com/services/TOKEN

  - name: "tg"
    type: "telegram"
    token: telegram:TOKEN
    chatID: chatIDStr

  - name: "email"
    type: "email"
    email: [receive@email.com,receive2@email.com]

  - name: "element"
    type: "element"
    roomID: "!id:matrix.org"
    sender: matrix # match matrix.name

email:
  type: smtp  #  sendgrid | smtp
  sender: "email"
  host: "smtp.*.com"
  port: 587
  user: "something"
  secret: "secret"

matrix:
  - name: martix
    host: https://matrix.org
    user:
    password: